name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
          cache: true

      - name: Test
        run: deno task lint

  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
          cache: true

      - name: Test
        run: |
          deno task test:coverage
          deno coverage --lcov --output=coverage.lcov

      - name: upload coverage
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          files: coverage.lcov
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
