name: release

on:
  push:
    branches:
      - beta
    #   - main

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
          cache: true

      - name: Test
        run: deno task lint

  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
          cache: true

      - name: Test
        run: |
          deno task test:coverage
          deno coverage --lcov --output=coverage.lcov

      - name: upload coverage
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          files: coverage.lcov
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
          cache: true

      - name: Build
        run: deno task build

      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
          if-no-files-found: error

  release:
    needs: [lint, test, build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      new_release: ${{ steps.semantic.outputs.new_release_published }}
      version: ${{ steps.semantic.outputs.new_release_version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    needs: [release]
    if: ${{ needs.release.outputs.new_release == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: denoland/setup-deno@v2
        with:
          deno-version: vx.x.x

      - uses: actions/download-artifact@v5
        with:
          name: dist
          path: dist

      - name: publish
        run: deno publish --set-version=${{ needs.release.outputs.version }} --allow-dirty
